version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movilidad
    ports:
      - "5432:5432"
    volumes:
      - ./datos:/datos
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    restart: unless-stopped
    environment:
      SUPERSET_SECRET_KEY: 'thisISaSECRET_key'
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_FIRSTNAME: Superset
      ADMIN_LASTNAME: Admin
      ADMIN_EMAIL: admin@superset.com
    ports:
      - "8088:8088"
    volumes:
      - superset-data:/app/superset_home
    depends_on:
      - postgres
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes:
  pgadmin-data:
  superset-data:
